name    'jhoblitt-megaraid'
version '0.0.2'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/jhoblitt/puppet-megaraid'
source 'https://github.com/jhoblitt/puppet-megaraid.git'
summary 'installs the LSI MegaRAID Storage Manager and MegaCLI RAID controller management software'
description 'installs the LSI MegaRAID Storage Manager and MegaCLI RAID controller management software'
dependency 'maestrodev/wget', '>= 0.0.1'
